"use strict";
exports.__esModule = true;
var backimgui_1 = require("./backimgui");
var embed_movie_1 = require("./embed_movie");
var keyshortcut_1 = require("./keyshortcut");
var mediaui_1 = require("./mediaui");
var movie_1 = require("./movie");
movie_1.movieJS(document);
mediaui_1.mediaUI(document);
backimgui_1.bgImgUI(document);
embed_movie_1.embedMovie(document);
keyshortcut_1.spaceShortcut(document);
